name: C/C++ CI (CMake)

on:
  push:
    branches: ["ci_test"]     # или ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install build deps
      run: sudo apt-get update && sudo apt-get install -y cmake build-essential

    - name: Configure (CMake)
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build -- -j$(nproc)

    - name: Run tests
      run: cd build && ctest --output-on-failure
